export { Message } from './message/Message.tsx'
export { Auth } from './auth/Auth.tsx'
export { Friends } from './friends/Friends.tsx'
export { Home } from './home/Home.tsx'
export { Profile } from './profile/Profile.tsx'
export { Register } from './register/Register.tsx'
export { Messages } from './messages/Messages.tsx'
